### PR TITLE
[WIP] Support latest TFLite and tweaks to Segmented Pings

### PR DESCRIPTION
**Pull request by topherwhite**
Also merged with develop that includes swarm functionality.

### CODE REVIEW

**Comment by Tooseriuz** [comment]
thank you @topherwhite , we decided to still not to use this branch yet and will update from [0.8.2](https://github.com/rfcx/rfcx-guardian-android/releases/tag/0.8.2-fix) instead and mark it as 0.8.8 and 0.8.9 for guardian and admin role to PR guardians so that there won't be swarm integration works mixed in this project.

**Comment by topherwhite** [comment]
Ok sounds good.

**Comment by antonyharfield** [comment]
@Tooseriuz we will need to take at least the TFLite updates from this branch to be able to run any recent models.

**Comment by Tooseriuz** [comment]
merged to the current develop branch

**Pull request closed without merging**
